### ISSUE TITLE
slow build

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/building-blocks#212] opened 2017-05-17 18:46 UTC
I am seeing very slow build times. Is everything being re-compiled or just the changed elements?

````bash
[14:42:31] Starting 'reload'...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[14:42:31] Finished 'reload' after 15 ms
[14:44:14] Starting 'building-block-pages'...
[14:44:14] Starting 'buildingBlockFrameLayouts'...
[14:44:18] Finished 'buildingBlockFrameLayouts' after 3.45 s
[14:44:18] Starting 'buildingBlockIframe'...
[14:44:25] Finished 'buildingBlockIframe' after 7.05 s
[14:44:25] Starting 'buildingBlockPage'...
[14:44:42] Finished 'buildingBlockPage' after 17 s
[14:44:42] Finished 'building-block-pages' after 28 s
[14:44:42] Starting 'building-block-indices'...
[14:44:42] Starting 'buildingBlocksCategoryStarters'...
[14:44:45] Finished 'buildingBlocksCategoryStarters' after 2.84 s
[14:44:45] Starting 'buildingBlocksCategoryPages'...
[14:44:46] Finished 'buildingBlocksCategoryPages' after 1.25 s
[14:44:46] Finished 'building-block-indices' after 4.08 s
[14:44:46] Starting 'reload'...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[14:44:46] Finished 'reload' after 4.78 ms
````

**Comment by IamManchanda** [comment] 2017-05-17 18:53
Dupe of #141
Yes it's very frustrating!

**Closed** 2017-05-18 03:18 UTC
